export const Routes = {
    root: "/",
    agencySplash: "/:id",
    splash: "/splash",
    app: "/",
    applicant: {
        dashboard: "/applicant/dashboard",
        application: "/applicant/application",
        documents: "/applicant/documents",
        helpCenter: "/applicant/help-center",
        settings: "/applicant/settings",
        profile: "/applicant/profile",
    },
    agency: {
        dashboard: "/agency/dashboard",
        dspManagement: "/agency/dsp-management",
        clients: "/agency/clients",
        addClient: "/agency/clients/add",
        editClient: "/agency/clients/edit/:clientId",
        clientDetails: "/agency/clients/:clientId",
        communityInclusions: "/agency/community-inclusions",
        communityInclusionHistory: "/agency/community-inclusions/history",
        billingAndApprovals: "/agency/billing-and-approvals",
        clientClaims: "/agency/billing-and-approvals/client/:clientId",
        dspClaims: "/agency/billing-and-approvals/dsp/:dsp",
        aiAutomation: "/agency/automations",
        scheduling: "/agency/scheduling",
        support: "/agency/support",
        analytics: "/agency/analytics",
        applicantDirectory: "/agency/applicant-directory",
        applicantClearanceHiring: "/agency/applicant-directory/clearance-hiring",
        applicantPendingApplicants: "/agency/applicant-directory/pending-applicants",
        applicantProfile: "/agency/applicant-directory/:id/profile",
        applicantDocuments: "/agency/applicant-directory/:id/documents",
        applicantConditionalHire: "/agency/applicant-directory/:id/conditional-hire",
        applicantFinalReview: "/agency/applicant-directory/:id/final-review",
        reports: "/agency/reports",
        trainings: "/agency/trainings",
        complianceAlerts: "/agency/compliance-alerts",
        shifts: "/agency/dashboard/shifts",
        shiftsList: "/agency/scheduling/shifts",
        approvals: "/agency/scheduling/approvals",
        activityLogs: "/agency/scheduling/activity-logs",
        notes: "/agency/notes",
        mileage: "/agency/mileage",
        helpCenter: "/agency/help-center",
        settings: "/agency/settings",
        profile: "/agency/profile",
    },
    userPanel: {
        dashboard: "/user-panel/dashboard",
        shiftManagement: "/user-panel/shift-management",
        manualShiftManagement: "/user-panel/shift-management/manual",
        clientsAndServices: "/user-panel/clients-and-services",
        planOfCare: "/user-panel/plan-of-care",
        notes: {
            index: "/user-panel/notes",
            communityBased: "/user-panel/notes/community-based",
            communityInclusion: "/user-panel/notes/community-inclusion",
            dayHabilitation: "/user-panel/notes/day-habilitation",
            preVocationalTraining: "/user-panel/notes/prevocational-training",
            respiteLog: "/user-panel/notes/respite-log",
            supportedEmploymentIntervention: "/user-panel/notes/supported-employment-intervention",
            supportedEmploymentPre: "/user-panel/notes/supported-employment-pre",
        },
        mileage: "/user-panel/mileage",
        expenses: "/user-panel/expenses",
        helpCenter: "/user-panel/help-center",
        settings: "/user-panel/settings",
        profile: "/user-panel/profile",
        communityInclusion: "/user-panel/community-inclusion",
    },
    superAdmin: {
        dashboard: "/super-admin/dashboard",
        agencies: "/super-admin/agencies",
        addAgency: "/super-admin/agencies/add",
        savedAgencies: "/super-admin/agencies/saved",
        agencyView: "/super-admin/agencies/:id",
        userAccessControl: "/super-admin/user-access-control",
        complianceMonitor: "/super-admin/compliance-monitor",
        globalNotesQuality: "/super-admin/global-notes-quality",
        agencyBillingMonitor: "/super-admin/agency-billing-monitor",
        corporateSupport: "/super-admin/corporate-support",
        oversightCenter: "/super-admin/oversight-center",
        clientDirectory: "/super-admin/clients",
        clientDetails: "/super-admin/clients/:clientId",
        editClient: "/super-admin/clients/edit/:clientId",
        addClient: "/super-admin/clients/add",
        reports: {
            index: "/super-admin/reports",
            clients: "/super-admin/reports/clients",
            dsp: "/super-admin/reports/dsp",
            shifts: "/super-admin/reports/shifts",
            notes: "/super-admin/reports/notes",
        },
        clientReports: "/super-admin/reports/clients",
        systemSettings: "/super-admin/system-settings",
    },
    auth: {
        login: "/auth/login",
        signup: "/auth/signup",
        forgotPassword: "/auth/forgot-password",
        resetPassword: "/auth/reset-password",
    },
    onboarding: {
        index: "/onboarding",
        email: "/onboarding/email",
        otp: "/onboarding/otp",
        success: "/onboarding/success",
    },
    common: {
        helpCenter: "/:userType/help-center",
        settings: "/:userType/settings",
        profile: "/:userType/profile",
    }
};