export const Routes = {
  root: "/",
  splash: "/splash",
  app: "/",
  applicant: {
    dashboard: "/applicant/dashboard",
    application: "/applicant/dashboard/application",
    documents: "/applicant/dashboard/documents",
    helpCenter: "/applicant/dashboard/help-center",
    settings: "/applicant/dashboard/settings",
    profile: "/applicant/dashboard/profile",
  },
  agency: {
    dashboard: "/agency/dashboard",
    dspManagement: "/agency/dsp-management",
    clients: "/agency/clients",
    billingAndApprovals: "/agency/billing-and-approvals",
    aiAutomation: "/agency/automations",
    scheduling: "/agency/scheduling",
    analytics: "/agency/analytics",
    applicantDirectory: "/agency/applicant-directory",
    reports: "/agency/reports",
    complianceAlerts: "/agency/dashboard/compliance-alerts",
    shifts: "/agency/dashboard/shifts",
    notes: "/agency/notes",
    helpCenter: "/agency/dashboard/help-center",
    settings: "/agency/dashboard/settings",
    profile: "/agency/dashboard/profile",
  },
  userPanel: {
    dashboard: "/user-panel/dashboard",
    shiftManagement: "/user-panel/shift-management",
    manualShiftManagement: "/user-panel/shift-management/manual",
    clientsAndServices: "/user-panel/clients-and-services",
    planOfCare: "/user-panel/plan-of-care",
    notes: {
      index: "/user-panel/notes",
      communityBased: "/user-panel/notes/community-based",
      communityInclusion: "/user-panel/notes/community-inclusion",
      dayHabilitation: "/user-panel/notes/day-habilitation",
      preVocationalTraining: "/user-panel/notes/prevocational-training",
      respiteLog: "/user-panel/notes/respite-log",
      supportedEmploymentIntervention: "/user-panel/notes/supported-employment-intervention",
      supportedEmploymentPre: "/user-panel/notes/supported-employment-pre",
    },
    mileage: "/user-panel/mileage",
    expenses: "/user-panel/expenses",
    helpCenter: "/user-panel/help-center",
    settings: "/user-panel/settings",
    profile: "/user-panel/profile",
  },
  auth: {
    login: "/auth/login",
    signup: "/auth/signup",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  onboarding: {
    index: "/onboarding",
    email: "/onboarding/email",
    otp: "/onboarding/otp",
    success: "/onboarding/success",
  },
  common: {
    helpCenter: "/:userType/help-center",
    settings: "/:userType/settings",
    profile: "/:userType/profile",
  }
};