export const Routes = {
  root: "/",
  splash: "/splash",
  app: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  onboarding: "/onboarding",
  onboardingEmail: "/onboarding/email",
  onboardingOTP: "/onboarding/otp",
  onboardingSuccess: "/onboarding/success",
  dashboard: "/dashboard",
  application: "/application",
  documents: "/documents",
  helpCenter: "/help-center",
  settings: "/settings",
  profile: "/profile",
};