import type { AddClientFormData } from "../types/formData";

/** Trimmed wizard context for POC generation (bounded payload). */
export function buildPocFormContext(formData: AddClientFormData): Record<string, unknown> {
  const { stage1, stage2, stage3, stage6 } = formData;

  return {
    stage1: {
      firstName: stage1.firstName,
      lastName: stage1.lastName,
      middleName: stage1.middleName,
      gender: stage1.gender,
      dob: stage1.dob?.toISOString?.() ?? stage1.dob,
      medicaidId: stage1.medicaidId,
      dddId: stage1.dddId,
      address: stage1.address,
      countyState: stage1.countyState,
      zipCode: stage1.zipCode,
      phone: stage1.phone,
      email: stage1.email,
      language: stage1.language,
      program: stage1.program,
      planId: stage1.planId,
    },
    stage2: {
      guardianName: stage2.guardianName,
      guardianRelationship: stage2.guardianRelationship,
      guardianEmail: stage2.guardianEmail,
      guardianPhone: stage2.guardianPhone,
      supportCoordinatorName: stage2.supportCoordinatorName,
      supportCoordinatorAgency: stage2.supportCoordinatorAgency,
      supportCoordinatorContact: stage2.supportCoordinatorContact,
      guardians: stage2.guardians,
      careTeam: stage2.careTeam,
      outcomes: stage2.outcomes?.map((o) => ({
        statement: o.statement,
        services: o.services?.map((s) => ({
          name: s.name,
          code: s.code,
          provider: s.provider,
          totalUnits: s.totalUnits,
          totalHours: s.totalHours,
          clientRate: s.clientRate,
          startAuthDate: s.startAuthDate?.toISOString?.() ?? s.startAuthDate,
          endAuthDate: s.endAuthDate?.toISOString?.() ?? s.endAuthDate,
          narrative: s.narrative,
        })),
      })),
    },
    stage3: {
      diagnosis: stage3.diagnosis,
      medicalConditions: stage3.medicalConditions,
      allergies: stage3.allergies,
      dietaryRestrictions: stage3.dietaryRestrictions,
      seizurePlan: stage3.seizurePlan,
      mobilitySupportNeeds: stage3.mobilitySupportNeeds,
      behaviorSupportPlan: stage3.behaviorSupportPlan,
      communicationNeeds: stage3.communicationNeeds,
      emergencyProtocols: stage3.emergencyProtocols,
      healthHazards: stage3.healthHazards,
      nutritionNotes: stage3.nutritionNotes,
      selfCareNeeds: stage3.selfCareNeeds,
    },
    stage6: {
      clientGoals: stage6.clientGoals,
      communityGoals: stage6.communityGoals,
      dailyLivingGoals: stage6.dailyLivingGoals,
      behavioralGoals: stage6.behavioralGoals,
      skillBuildingGoals: stage6.skillBuildingGoals,
      ispOutcomes: stage6.ispOutcomes,
      targetBehaviors: stage6.targetBehaviors,
      supportStrategies: stage6.supportStrategies,
      emergencyName: stage6.emergencyName,
      emergencyRelationship: stage6.emergencyRelationship,
      primaryPhone: stage6.primaryPhone,
      secondaryPhone: stage6.secondaryPhone,
      hospitalPreference: stage6.hospitalPreference,
      emergencyProtocol: stage6.emergencyProtocol,
      medicationList: stage6.medicationList,
      medications: stage6.medications,
      emergencyContacts: stage6.emergencyContacts,
      emergencyBackupPlan: stage6.emergencyBackupPlan,
    },
  };
}
