name: Deploy Pipeline
on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

  sync-and-deploy:
    name: Mirror to Deployment Repo
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    env:
      GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
    steps:
      - name: Mirror to target repo
        run: |
          gh auth setup-git
          gh repo clone https://github.com/MyCareOnBoardOrg/CareOnBoard-Web.git
          cd CareOnBoard-Web
          rm .github/workflows/deploy-to-vercel.yml
          git config user.email "info@joincareonboard.com"
          git config user.name "MyCareOnBoard"
          git add .
          git commit -m "Remove GitHub Actions workflows"
          git remote add target https://github.com/MyCareOnBoard/CareOnBoard-Web-Deployment.git
          git push target main --force
